services:
  - type: web
    name: linebot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: RENDER_URL
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
    plan: free
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 50
      targetCPUPercent: 50
  - type: cron
    name: morning-notification
    env: python
    schedule: "0 8 * * *"
    buildCommand: pip install -r requirements.txt
    startCommand: python notify.py
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
  - type: cron
    name: afternoon-notification
    env: python
    schedule: "0 12 * * *"
    buildCommand: pip install -r requirements.txt
    startCommand: python notify.py
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false 